import Menu from "@/component/menu";
import Head from "next/head";

const AddRecipe = () => {
  return (
    <>
      <Head>
        <title>Add new recipe</title>
        <meta name="cook web" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="add-recipe-header">
        <Menu />
        <div className="home-text-hero">
          <span className="add-recipe-hero">Add New Recipe</span>
        </div>
      </div>
      <div className="add-recipe-box">
        <div className="rec-ins-ing">
          <label htmlFor="recipe-name">Recipe name:</label>
          <input type="text" id="recipe-name" name="recipe-name"></input>
          <label htmlFor="instructions">Instructions:</label>
          <input type="text" id="instructions" name="instructions"></input>
          <label htmlFor="ingredients">Ingredients:</label>
          <input type="text" id="ingredients" name="ingredients"></input>
        </div>
        <div className="prep-serve">
          <div className="prep-field">
            <label>Prep time:</label>
            <input type="number"></input>
          </div>
          <div className="serve-field">
            <label>Serves:</label>
            <input type="number"></input>
          </div>
        </div>
        <div className="img-url">
          <label>Image URL:</label>
          <input type="url"></input>
        </div>
        <div className="category-field">
          <p>Category:</p>
          <div className="checkboxes">
            <div className="ind-check">
              <label htmlFor="breakfast">Breakfast</label>
              <input type="checkbox" id="breakfast" name="breakfast"></input>
            </div>
            <div className="ind-check">
              <label htmlFor="lunch">Lunch</label>
              <input type="checkbox" id="lunch" name="lunch"></input>
            </div>
            <div className="ind-check">
              <label htmlFor="dinner">Dinner</label>
              <input type="checkbox" id="dinner" name="dinner"></input>
            </div>
            <div className="ind-check">
              <label htmlFor="dessert">Dessert</label>
              <input type="checkbox" id="dessert" name="dessert"></input>
            </div>
          </div>
        </div>
        <div className="add-buttons">
          <button id="save-recipe">Save</button>
          <button id="cancel-recipe">Cancel</button>
        </div>
      </div>
    </>
  );
};

export default AddRecipe;
