import Head from "next/head";
import { Inter } from "next/font/google";
import Menu from "../component/menu";
import Button from "../component/butten";
import RecipeList from "@/component/filter";
import { useEffect } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    // ??????
    const getMe = async (token: string) => {
      const response = await axios.get("http://localhost:3001/me", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      // Вход в систему
      console.log(response.data);
    };
    const token = localStorage.getItem("token");
    if (token === null) {
      return;
    }
    getMe(token);
  });
  return (
    <>
      <Head>
        <title>Hello I am a the bug 🪲</title>
        <meta name="cook web" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="home-hero-header">
        <Menu />
        <div className="home-text-hero">
          <span className="home-chef-hero">Home</span>
          <span className="home-chef-hero">Chef</span>
          <span className="home-chef-hero">Recipes</span>
        </div>
      </div>
      <RecipeList />
      <section className="home-add-recipe">
        <span className="add-new-recipe">Add</span>
        <span className="add-new-recipe">New</span>
        <span className="add-new-recipe">Recipes</span>
      </section>
    </>
  );
}
