import Head from "next/head";
import { Inter } from "next/font/google";
import Menu from "../component/menu";
import RecipeList from "@/component/filter";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Chef Recipes</title>
        <meta name="cook web" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="home-hero-header">
        <Menu />
        <div className="home-text-hero">
          <span className="home-chef-hero">Home</span>
          <span className="home-chef-hero">Chef</span>
          <span className="home-chef-hero">Recipes</span>
        </div>
      </div>
      <RecipeList />
      <Link className={"link-style"} href="/add-recipe">
        <section className="home-add-recipe">
          <span className="add-new-recipe">Add</span>
          <span className="add-new-recipe">New</span>
          <span className="add-new-recipe">Recipes</span>
        </section>
      </Link>
    </>
  );
}
