import Head from "next/head";
import { Inter } from "next/font/google";
import Menu from "../component/menu";
import Recipes from "../component/recipes";
import Categories from "../component/categories";
import Button from "../component/butten";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Chef Recipes</title>
        <meta name="cook web" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Menu roundedCorners={false} /> */}
      <nav className="recipes-navigation-bar"></nav>

      <h1>Home Chef Recipes</h1>
      <Recipes />
      <Button />
    </>
  );
}
